fastlane_version "2.46.1"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Radioish', export_method: 'development')

    emails = values[:test_email] ? values[:test_email] : ['bigbryanloon@gmail.com', 'redgnarly@gmail.com', 'jeffharder@me.com', 'cloewen6@gmail.com', 'chris@oldmare.com', 'paul@creativehydra.com', 'excitephotography@gmail.com', 'jeremyklassen@mac.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'b8797e3a99e9fee48e7423bc6aeb6b458142edf4',
             build_secret: 'e13c1abf5fbc19cd1627dfb7abbe1955602c3c52f553785a0390f1a80b8734d1',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    slack(
      slack_url: "https://hooks.slack.com/services/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",
      channel: "development",
      message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    )
  end
end
